const DEFINE_STATUS = {
  PENDING_APPROVAL: "PENDING_APPROVAL",
  ACCEPTED: "ACCEPTED",
  DENIED: "DENIED",
  CANCELED: "CANCELED",
};

const DEFINE_SCHEDULE_STATUS = {
  AVAILABLE: "AVAILABLE",
  NOT_AVAILABLE: "NOT_AVAILABLE",
}


export { DEFINE_STATUS, DEFINE_SCHEDULE_STATUS };
